export const BRAND = {
  name: 'CertaintyAI',
  trademark: '™',
  maker: 'MDxBlocks Inc.',
  tagline: 'Defensible AI for regulated industries',
  positioning: 'Open Architecture for Governed Agentic AI',
  positioningEyebrow: 'OPEN ARCHITECTURE FOR GOVERNED AGENTIC AI',
  trustStrip: [
    'Built on Google Cloud',
    'Vertex AI',
    'NIST AI RMF',
    'ISO 42001',
    'EU AI Act',
    'Apache-2.0',
  ],
}

export const CTA = {
  exploreArchitecture: { label: 'Explore the Architecture', href: '/architecture' },
  startFree:           { label: 'Start free',                href: '/signup' },
  readinessCheck:      { label: '2-min Readiness Check',     href: '/survey' },
  bookReview:          { label: 'Book a 20-min architecture review', href: '/signup' },
}

export const NARRATIVE_CHAIN = [
  {
    id: 'open-architecture',
    index: 1,
    title: 'Open Architecture',
    blurb: 'One layered backbone. Open standards on every seam — so agents, data, and policies stay portable.',
    caps: ['A2A', 'MCP', 'W3C', 'OpenLineage', 'ISO 42001'],
    cta: { label: 'See the 6-layer stack', href: '#architecture-stack' },
    accent: '#A87C3C',
    glow: 'rgba(168,124,60,0.18)',
  },
  {
    id: 'ontology-fabric',
    index: 2,
    title: 'Ontology Intelligence Fabric',
    blurb: 'The trusted model of your business — what each thing means, how it relates, and which rules govern it.',
    caps: ['W3C Semantics', 'SNOMED · LOINC · ICD-10', 'GraphRAG', 'Versioning'],
    cta: { label: 'Read the ontology spec', href: '/architecture' },
    accent: '#2F7D6B',
    glow: 'rgba(47,125,107,0.18)',
  },
  {
    id: 'governance-trust',
    index: 3,
    title: 'Governance & Trust Layer',
    blurb: 'Policy, lineage, and evidence packs. Every answer cites the data, ontology term, and rule behind it.',
    caps: ['Active Policy Engine', 'Evidence Pack', 'NIST GOVERN/MEASURE', 'Catalog Adapters'],
    cta: { label: 'See the trust contract', href: '/architecture' },
    accent: '#D8B061',
    glow: 'rgba(216,176,97,0.22)',
  },
  {
    id: 'orchestration',
    index: 4,
    title: 'Multi-Agent Orchestration',
    blurb: 'Agents reason, plan, and call tools — under your policies. Powered by Google ADK, A2A across processes, and MCP.',
    caps: ['ADK SequentialAgent', 'A2A v0.3.0', 'MCP Tools', 'Vertex AI Gemini'],
    cta: { label: 'Watch the live A2A handshake', href: '/architecture' },
    accent: '#C77A57',
    glow: 'rgba(199,122,87,0.18)',
  },
  {
    id: 'copilots',
    index: 5,
    title: 'Domain AI Copilots',
    blurb: 'Pre-built copilots for CISO and CFO. Build your own in minutes — with role templates, knowledge bases, and step traces.',
    caps: ['Role Templates', 'Knowledge Base RAG', 'Voice', 'Step Traces'],
    cta: { label: 'Explore the Copilots', href: '/copilots' },
    accent: '#A8506A',
    glow: 'rgba(168,80,106,0.18)',
  },
  {
    id: 'control-tower',
    index: 6,
    title: 'AI Control Tower',
    blurb: 'One view of every agent, every decision, every cost. Policy violations, spend, and confidence at a glance.',
    caps: ['Run Inventory', 'Policy Violations', 'Spend & FinOps', 'NIST sub-scores'],
    cta: { label: 'Tour the Control Tower', href: '/signup' },
    accent: '#3A7E92',
    glow: 'rgba(58,126,146,0.18)',
  },
  {
    id: 'outcomes',
    index: 7,
    title: 'Business Outcomes',
    blurb: 'What this stack lets you actually do — flagship use cases, audit-ready reports, Marketplace listings.',
    caps: ['AI Readiness Assessment', 'Vendor Risk Triage', 'AI ROI Analyzer', 'Marketplace-ready'],
    cta: { label: 'Take the 2-min Readiness Check', href: '/survey' },
    accent: '#3B6688',
    glow: 'rgba(59,102,136,0.18)',
  },
]
